### ISSUE TITLE
업데이트가 안되는것 같습니다

### ISSUE THREAD

**Issue by LEEYEONGJAE1** [mazassumnida/mazacofo#4]
<img width="272" alt="image" src="https://github.com/mazassumnida/mazacofo/assets/41511949/f4cfb2e1-7f0e-420c-935e-b63596e84a9e">

5월 5일에 점수가 갱신됐는데 

<img width="360" alt="image" src="https://github.com/mazassumnida/mazacofo/assets/41511949/a7167854-85e9-4165-8288-c63f7657a447">

깃허브 프로필에 이전 점수가 뜨네요

**Comment by dongzoolee** [comment]
@LEEYEONGJAE1 버그를 발견하여 수정했습니다. 리포트 주셔서 감사합니다 🙏

**Comment by LEEYEONGJAE1** [comment]
👍
